### ISSUE TITLE
CRを消してほしい

### ISSUE THREAD

**Issue by theoldmoon0602** [kekeho/SGWeb#13]
Windows環境でエディットすると改行文字がCRLFになるんですが、このCRが邪魔になるケースがあるので適当なタイミングで削除してほしいです

（たとえば以下はCRLFだと `/usr/bin/python\r` が存在しないとして怒られます）
```
#/usr/bin/python
print("HELLO")
```

**Comment by kekeho** [comment]
a999cd4ffca3e6439d7
これでどうですか? 手元にWin環境がないので試していただけるとありがたいです。

**Comment by theoldmoon0602** [comment]
@kekeho 私もすぐには準備できないので、環境がととのったらまた結果を報告します

**Comment by Khronos31** [comment]
Windows環境とiPhoneで確認しました。修正できているように見えます。

**Comment by kekeho** [comment]
ありがとうございます。Masterにマージします。
